'use client'
import { useState } from 'react'
import type { Handoff, HandoffStatus } from '@/lib/flux-repository'
import styles from '../page.module.css'
const labels: Record<string,string> = { received:'Recebido', in_progress:'Em evolução', blocked:'Bloqueado', released:'Liberado', completed:'Concluído', legacy:'Legado' }
export default function HandoffsClient({ initial }: { initial: Handoff[] }) {
 const [items,setItems]=useState(initial), [selected,setSelected]=useState<Handoff|null>(null), [query,setQuery]=useState(''), [message,setMessage]=useState('')
 const filtered=items.filter(h=>`${h.id} ${h.summary} ${h.from} ${h.to} ${h.cardId} ${h.project}`.toLowerCase().includes(query.toLowerCase()))
 async function act(action:'resume'|'release') { if(!selected)return; const solution=selected.solution; if(!solution){setMessage('Ação bloqueada: solução não declarada');return} const correlationId=crypto.randomUUID(); const r=await fetch(`/api/flux/handoffs/${selected.id}/resume`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,correlationId,cause:solution.cause,solution:solution.resolutionPlan,nextAction:solution.nextAction,owner:solution.owner})}); const body=await r.json(); if(!r.ok){setMessage(`${body.error}: ${body.message}`);return} setItems(items.map(h=>h.id===selected.id?body.handoff:h));setSelected(body.handoff);setMessage(body.idempotent?'Liberação já registrada (idempotente)':'Handoff atualizado sem concluir o trabalho') }
 return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>FBR Agency / Control Tower</p><h1>Handoffs</h1><p className={styles.subtitle}>Espaço detalhado para continuidade operacional · snapshot não equivale ao histórico completo</p></div><nav><a href="/">Dashboard</a> · <a href="/api/flux/jobs">Jobs</a></nav></header>
 <div className={styles.toolbar}><label>Pesquisar Handoffs<input aria-label="pesquisar Handoffs" value={query} onChange={e=>setQuery(e.target.value)} placeholder="título, card, de/para"/></label><a href="/">Voltar ao dashboard</a></div>{message&&<div role="status" className={styles.notice}>{message}</div>}
 <section className={styles.panel}><div className={styles.panelHeader}><h2>Últimos Handoffs</h2></div><div className={styles.handoffGrid}>{filtered.slice(0,6).map(h=><button className={styles.handoffCard} key={h.id} onClick={()=>setSelected(h)}><strong>{h.summary}</strong><div><Status value={h.status||'received'}/></div><small>{h.lastBlocker||h.lastRelease||'sem blocker/liberação registrada'}</small></button>)}</div></section>
 <section className={styles.panel}><div className={styles.panelHeader}><h2>Todos os Handoffs <span className={styles.muted}>({filtered.length})</span></h2></div><div className={styles.handoffList}>{filtered.map(h=><button key={h.id} onClick={()=>setSelected(h)}><span>{h.summary}</span><span>{h.cardId}</span><Status value={h.status||'received'}/></button>)}</div></section>
 {selected&&<div className={styles.detail} role="dialog" aria-label="detalhes do Handoff"><div className={styles.row}><h2>{selected.summary}</h2><button onClick={()=>setSelected(null)}>Fechar</button></div><p><strong>Status:</strong> <Status value={selected.status||'received'}/> · <strong>De/para:</strong> {selected.from} → {selected.to}</p><p><strong>Card/job:</strong> {selected.cardId} / {selected.jobId||'não declarado'}</p><p><strong>Resumo:</strong> {selected.summary}</p><p><strong>Done:</strong> {selected.done||'não informado'}</p><p><strong>Riscos:</strong> {selected.risks||'não informado'}</p><p><strong>Blockers:</strong> {selected.lastBlocker||'não registrado'}</p><p><strong>Owner:</strong> {selected.solution?.owner||selected.to||'não declarado'}</p><p><strong>Solução:</strong> {selected.solution?.resolutionPlan||'não declarada'}</p><p><strong>Próximo passo:</strong> {selected.nextStep||'não registrado'}</p><p><strong>Evidência:</strong> {selected.evidenceRef||'não declarada'}</p><p><strong>Origem:</strong> {selected.source||selected.sourceType||'não declarada'} · {selected.historical?'histórico derivado':'registro persistido'}</p><div className={styles.actions}><button disabled={selected.status==='legacy'||selected.historical||!selected.solution} title={selected.status==='legacy'||selected.historical?'Handoff legacy é somente leitura':!selected.solution?'solução não declarada':undefined} onClick={()=>act('resume')}>Retomar evolução</button><button disabled={selected.status==='legacy'||selected.historical||!selected.solution} title={selected.status==='legacy'||selected.historical?'Handoff legacy é somente leitura':!selected.solution?'solução não declarada':undefined} onClick={()=>act('release')}>Liberar para owner</button></div>{(selected.status==='legacy'||selected.historical)&&<small role="note">Desabilitado: este Handoff é histórico/legacy e não pode sofrer mutação.</small>}{!selected.solution&&<small role="note">Desabilitado: solução, owner e próximo passo precisam estar registrados.</small>}</div>}
 </main>
}
function Status({value}:{value:string}){return <span className={`${styles.status} ${styles[`status_${value}`]||''}`}>{labels[value]||value}</span>}
