'use client'
import Link from 'next/link'
import { useState } from 'react'
import type { Handoff, HandoffStatus } from '@/lib/flux-repository'
import styles from '../page.module.css'
const labels: Record<string,string> = { received:'Recebido', in_progress:'Em evolução', awaiting_owner:'Aguardando owner', blocked:'Bloqueado', released:'Liberado', completed:'Concluído', legacy:'Histórico/legacy' }
export default function HandoffsClient({ initial }: { initial: Handoff[] }) {
 const [items,setItems]=useState(initial), [selected,setSelected]=useState<Handoff|null>(null), [query,setQuery]=useState(''), [message,setMessage]=useState('')
 const filtered=items.filter(h=>`${h.id} ${h.summary} ${h.from} ${h.to} ${h.cardId} ${h.project}`.toLowerCase().includes(query.toLowerCase()))
 async function act(action:'resume'|'release') { if(!selected)return; const legacy=Boolean(selected.historical||selected.legacy||selected.status==='legacy'); const solution=selected.solution; if(!legacy&&!solution){setMessage('Ação bloqueada: solução/owner/próximo passo não declarados');return} const correlationId=crypto.randomUUID(); const r=await fetch(`/api/flux/handoffs/${selected.id}/resume`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(legacy?{action:'resume',correlationId,nextAction:selected.nextStep,owner:selected.to}:{action,correlationId,cause:solution!.cause,solution:solution!.resolutionPlan,nextAction:solution!.nextAction,owner:solution!.owner})}); const body=await r.json(); if(!r.ok){setMessage(`${body.error}: ${body.message}`);return} if(body.handoff?.id!==selected.id){setItems([...items,body.handoff]);setSelected(body.handoff)}else{setItems(items.map(h=>h.id===selected.id?body.handoff:h));setSelected(body.handoff)}setMessage(body.idempotent?'Retomada/liberação já registrada (idempotente)':'Registro operacional criado sem concluir o trabalho') }
 return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>FBR Agency / Control Tower</p><h1>Handoffs</h1><p className={styles.subtitle}>Espaço detalhado para continuidade operacional · snapshot não equivale ao histórico completo</p></div><nav><Link href="/">Dashboard</Link> · <Link href="/api/flux/jobs">Jobs</Link></nav></header>
 <div className={styles.toolbar}><label>Pesquisar Handoffs<input aria-label="pesquisar Handoffs" value={query} onChange={e=>setQuery(e.target.value)} placeholder="título, card, de/para"/></label><Link href="/">Voltar ao dashboard</Link></div>{message&&<div role="status" className={styles.notice}>{message}</div>}
 <section className={styles.panel}><div className={styles.panelHeader}><h2>Últimos Handoffs</h2></div><div className={styles.handoffGrid}>{filtered.slice(0,6).map(h=><button className={styles.handoffCard} key={h.id} onClick={()=>setSelected(h)}><strong>{h.summary}</strong><div><Status value={h.status||'received'}/></div><small>{h.lastBlocker||h.lastRelease||'sem blocker/liberação registrada'}</small></button>)}</div></section>
 <section className={styles.panel}><div className={styles.panelHeader}><h2>Todos os Handoffs <span className={styles.muted}>({filtered.length})</span></h2></div><div className={styles.handoffList}>{filtered.map(h=><button key={h.id} onClick={()=>setSelected(h)}><span>{h.summary}</span><span>{h.cardId}</span><Status value={h.status||'received'}/></button>)}</div></section>
 {selected&&<div className={styles.detail} role="dialog" aria-label="detalhes do Handoff"><div className={styles.row}><h2>{selected.summary}</h2><button onClick={()=>setSelected(null)}>Fechar</button></div><p><strong>Status:</strong> <Status value={selected.status||'received'}/> · <strong>De/para:</strong> {selected.from} → {selected.to}</p><p><strong>Card/job:</strong> {selected.cardId} / {selected.jobId||'não declarado'}</p><p><strong>Resumo:</strong> {selected.summary}</p><p><strong>Done:</strong> {selected.done||'não informado'}</p><p><strong>Riscos:</strong> {selected.risks||'não informado'}</p><p><strong>Blockers:</strong> {selected.lastBlocker||'não registrado'}</p><p><strong>Owner:</strong> {selected.solution?.owner||selected.to||'não declarado'}</p><p><strong>Solução:</strong> {selected.solution?.resolutionPlan||'não declarada'}</p><p><strong>Próximo passo:</strong> {selected.nextStep||'não registrado'}</p><p><strong>Evidência:</strong> {selected.evidenceRef||'não declarada'}</p><p><strong>Origem:</strong> {selected.source||selected.sourceType||'não declarada'} · {selected.historical?'histórico derivado':'registro persistido'}</p><div className={styles.actions}><button disabled={!selected.solution&&!selected.nextStep} title={!selected.solution&&!selected.nextStep?'nextStep/owner não declarados':undefined} onClick={()=>act('resume')}>Retomar evolução</button><button disabled={selected.status==='legacy'||selected.historical||selected.legacy||!selected.solution} title={selected.status==='legacy'||selected.historical||selected.legacy?'Handoff legacy só permite retomada':!selected.solution?'solução não declarada':undefined} onClick={()=>act('release')}>Liberar para owner</button></div>{(selected.status==='legacy'||selected.historical||selected.legacy)&&<small role="note">Legado preservado: a retomada cria novo registro e usa apenas nextStep/owner já declarados.</small>}{!selected.solution&&!selected.nextStep&&<small role="note">Falta solução/owner/próximo passo; ações operacionais desabilitadas.</small>}</div>}
 </main>
}
function Status({value}:{value:string}){return <span className={`${styles.status} ${styles[`status_${value}`]||''}`}>{labels[value]||value}</span>}
