import { createHash } from 'node:crypto'
import { FluxError, mutateState, getSnapshot, type LocalActor, type Sprint, type Story, type SprintStatus, type StoryStatus } from './flux-repository'
import { createReceipt } from './observability'
const now = () => new Date().toISOString()
const id = (kind: string, value: string) => `${kind}-${createHash('sha256').update(`${value}:${Date.now()}`).digest('hex').slice(0, 16)}`
function actorOk(actor: LocalActor) { if (!actor || actor.scope !== 'local' || !actor.actor.trim()) throw new FluxError('UNAUTHORIZED_ACTOR', 'Local actor is required', 403) }
export type SprintInput = { projectId: string; tenantId?: string; name: string; objective: string; status?: SprintStatus; owner: string; startsAt?: string; endsAt?: string; dependencies?: string[]; nextCheck: string }
export type StoryInput = { sprintId: string; projectId: string; tenantId?: string; title: string; objective: string; owner: string; acceptanceCriteria: string[]; status?: StoryStatus; cardIds?: string[]; jobIds?: string[]; evidenceRefs?: string[]; blockerIds?: string[]; nextCheck: string }
function required(value: string, name: string) { if (!value?.trim()) throw new FluxError('INVALID_PLANNING_ENTITY', `${name} is required`, 422) }
export async function listPlanning(file?: string) { const s = await getSnapshot(file); return { sprints: s.sprints || [], stories: s.stories || [] } }
export async function createSprint(input: SprintInput, actor: LocalActor, file?: string) { actorOk(actor); required(input.projectId, 'projectId'); required(input.name, 'name'); required(input.objective, 'objective'); required(input.owner, 'owner'); required(input.nextCheck, 'nextCheck'); if (Number.isNaN(Date.parse(input.nextCheck))) throw new FluxError('INVALID_NEXT_CHECK', 'nextCheck must be an ISO date', 422)
 return mutateState(state => { const project = state.projects.find(p => p.id === input.projectId); if (!project) throw new FluxError('PROJECT_NOT_FOUND', `Project ${input.projectId} not found`, 404); if (actor.tenantId && actor.tenantId !== (input.tenantId || project.tenantId)) throw new FluxError('TENANT_MISMATCH', 'Operation crosses tenant boundary', 403); const stamp = now(); const sprint: Sprint = { id: id('sprint', input.projectId), projectId: input.projectId, tenantId: input.tenantId || project.tenantId, name: input.name.trim(), objective: input.objective.trim(), status: input.status || 'planned', owner: input.owner.trim(), startsAt: input.startsAt, endsAt: input.endsAt, dependencies: input.dependencies || [], nextCheck: input.nextCheck, createdAt: stamp, updatedAt: stamp }; state.sprints = [...(state.sprints || []), sprint]; const correlationId = `planning-${sprint.id}`; const receipt = createReceipt({ correlationId, operation: 'sprint.create', status: 'completed', actor: actor.actor, metadata: { sprintId: sprint.id } }); state.events.push({ id: `event-${sprint.id}`, time: stamp, actor: actor.actor, action: 'created sprint', correlationId, reason: sprint.objective, receipt }); return { sprint, receipt } }, file) }
export async function createStory(input: StoryInput, actor: LocalActor, file?: string) { actorOk(actor); for (const [v,n] of [[input.sprintId,'sprintId'],[input.projectId,'projectId'],[input.title,'title'],[input.objective,'objective'],[input.owner,'owner'],[input.nextCheck,'nextCheck']] as const) required(v,n); if (!input.acceptanceCriteria?.length) throw new FluxError('INVALID_PLANNING_ENTITY', 'acceptanceCriteria is required', 422); if (Number.isNaN(Date.parse(input.nextCheck))) throw new FluxError('INVALID_NEXT_CHECK', 'nextCheck must be an ISO date', 422)
 return mutateState(state => { const sprint = (state.sprints || []).find(s => s.id === input.sprintId); if (!sprint || sprint.projectId !== input.projectId) throw new FluxError('SPRINT_NOT_FOUND', `Sprint ${input.sprintId} not found for project`, 404); const stamp = now(); const story: Story = { id: id('story', input.title), sprintId: input.sprintId, projectId: input.projectId, tenantId: input.tenantId || sprint.tenantId, title: input.title.trim(), objective: input.objective.trim(), owner: input.owner.trim(), acceptanceCriteria: input.acceptanceCriteria, status: input.status || 'planned', cardIds: input.cardIds || [], jobIds: input.jobIds || [], evidenceRefs: input.evidenceRefs || [], blockerIds: input.blockerIds || [], nextCheck: input.nextCheck, createdAt: stamp, updatedAt: stamp }; state.stories = [...(state.stories || []), story]; const correlationId = `planning-${story.id}`; const receipt = createReceipt({ correlationId, operation: 'story.create', status: 'completed', actor: actor.actor, metadata: { storyId: story.id } }); state.events.push({ id: `event-${story.id}`, time: stamp, actor: actor.actor, action: 'created story', correlationId, reason: story.objective, receipt }); return { story, receipt } }, file) }
