export type Field = { column: string; type: string; ref?: string }
export type EntitySpec = { table: string; key: string; fields: Record<string, Field> }
const snake = (s: string) => s.replace(/[A-Z]/g, c => `_${c.toLowerCase()}`).replaceAll('.', '_')
function fields(text: string, overrides: Record<string, string> = {}): Record<string, Field> {
  return Object.fromEntries(text.split(/\s+/).filter(Boolean).map(token => {
    const [key, kind = 'text', ref] = token.split(':')
    return [key, { column: overrides[key] || snake(key), type: kind === 'array' ? 'text[]' : kind, ...(ref ? { ref } : {}) }]
  }))
}
const resolution = 'from to objective deliverable acceptanceCriteria evidenceRequired nextStep fallback'
const solution = 'cause owner nextAction resolutionPlan resolutionEvidence'
const nested = (name: string, keys: string) => `${name}Present:boolean ` + keys.split(' ').map(k => `${name}.${k}`).join(' ')
/** Exhaustive, explicit domain -> SQL column contract. Unknown fields fail closed. */
export const relationalSpecs: Record<string, EntitySpec> = {
  projects: { table: 'flux_projects', key: 'id', fields: fields('name tenantId:uuid:tenants status owner description', { owner: 'owner_name' }) },
  cards: { table: 'flux_cards', key: 'id', fields: fields('project:uuid:projects tenantId:uuid:tenants title status assignee priority detail acceptanceCriteria:array updatedAt:timestamptz', { project: 'project_id', detail: 'objective', acceptanceCriteria: 'criteria_values' }) },
  approvals: { table: 'flux_approvals', key: 'id', fields: fields('cardId:uuid:cards tenantId:uuid:tenants title requestedBy impact scope rollback status decidedAt:timestamptz decidedBy', { scope: 'action_scope', rollback: 'rollback_plan', status: 'decision' }) },
  gates: { table: 'flux_gates', key: 'id', fields: fields('cardId:uuid:cards project:uuid:projects title requiredDecision status impact cost scope reversibility rollback evidence:array owner requestedAt:timestamptz decidedAt:timestamptz decidedBy externalActionAuthorized:boolean blockers:array', { project: 'project_id', rollback: 'rollback_plan', evidence: 'evidence_refs', blockers: 'blocker_refs' }) },
  jobs: { table: 'flux_jobs', key: 'jobId', fields: fields('cardId:uuid:cards project:uuid:projects tenantId:uuid:tenants agent role objective status startedAt:timestamptz updatedAt:timestamptz completedAt:timestamptz artifactRefs:array handoffRefs:array evidenceRefs:array blockers:array nextStep correlationId source sourceType historical:boolean activeBlocker:boolean lastSeen:timestamptz lastActivity nextCheck progress:integer currentStep owner lastEvent verification dependsOn:array blocks:array canStart:boolean parallelGroup track dependencyReason', { project: 'project_id', agent: 'agent_name', correlationId: 'correlation_ref', source: 'source_ref', sourceType: 'domain_source_type', verification: 'verification_status', lastSeen: 'last_seen_at', nextCheck: 'next_check_label' }) },
  handoffs: { table: 'flux_handoffs', key: 'id', fields: fields('cardId:uuid:cards project:uuid:projects from to summary done decisions:array risks nextStep nextCheck lastActivity acceptanceCriteria evidenceRef createdAt:timestamptz status lastUpdate lastBlocker lastRelease blockerId jobId:uuid:jobs correlationId forwardingKey sourceType historical:boolean legacy:boolean source activeBlocker:boolean ' + nested('resolutionAction', resolution) + ' ' + nested('interaction', resolution + ' actor type status decision message') + ' ' + nested('solution', solution), { project: 'project_id', from: 'from_actor', to: 'to_actor', correlationId: 'correlation_ref', nextCheck: 'next_check_label', source: 'source_ref' }) },
  artifacts: { table: 'flux_artifacts', key: 'id', fields: fields('cardId:uuid:cards name kind status path sourcePath size:bigint contentText contentBinary:bytea contentType', { kind: 'artifact_type', path: 'path_or_ref', contentText: 'content_text', contentBinary: 'content_binary' }) },
  blockers: { table: 'flux_blockers', key: 'id', fields: fields('sourceId cardId:uuid:cards cause status owner author nextAction resolutionPlan resolutionEvidence resolution verification ' + nested('resolutionAction', resolution), { verification: 'verification_status' }) },
  sprints: { table: 'flux_sprints', key: 'id', fields: fields('projectId:uuid:projects tenantId:uuid:tenants name objective status owner startsAt:timestamptz endsAt:timestamptz dependencies:array nextCheck createdAt:timestamptz updatedAt:timestamptz', { nextCheck: 'next_check_label' }) },
  stories: { table: 'flux_stories', key: 'id', fields: fields('sprintId:uuid:sprints projectId:uuid:projects tenantId:uuid:tenants title objective owner acceptanceCriteria:array status cardIds:array jobIds:array evidenceRefs:array blockerIds:array nextCheck createdAt:timestamptz updatedAt:timestamptz', { nextCheck: 'next_check_label', acceptanceCriteria: 'criteria_values' }) },
  requiredActions: { table: 'flux_required_actions', key: 'id', fields: fields('dedupeKey what why who from to objective deliverable acceptanceCriteria dueCheck fallback status reasonCode correlationId createdAt:timestamptz updatedAt:timestamptz', { from: 'from_actor', to: 'to_actor', dueCheck: 'due_check_label', correlationId: 'correlation_ref' }) },
  coordinatorRuns: { table: 'flux_coordinator_runs', key: 'correlationId', fields: fields('startedAt:timestamptz completedAt:timestamptz heartbeat:timestamptz lastActivity:timestamptz idleDetected:integer dispatched:integer holds:integer requiredActions:integer waitingReasons:array result lastCheck nextFollowUp unanswered:integer backlogActionable:integer', { heartbeat: 'heartbeat_at', lastActivity: 'last_activity_at', lastCheck: 'last_check_label', nextFollowUp: 'next_follow_up_label' }) },
  receipts: { table: 'flux_receipts', key: 'id', fields: fields('correlationId operation status actor jobId:uuid:jobs startedAt:timestamptz completedAt:timestamptz durationMs:integer ' + nested('metadata', 'cardId fromStatus status approvalId decision gateId handoffId blockerId artifactId projectId tenant eventId type sprintId storyId'), { correlationId: 'correlation_ref' }) },
  events: { table: 'flux_events', key: 'id', fields: fields('time:timestamptz actor action cardId:uuid:cards correlationId fromStatus toStatus reason blockerId jobId:uuid:jobs handoffId:uuid:handoffs from to owner nextAction receiptId:uuid:receipts ' + nested('solution', solution) + ' ' + nested('resolutionAction', resolution), { time: 'created_at', action: 'event_type', correlationId: 'correlation_ref', from: 'from_actor', to: 'to_actor' }) },
}
