'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { useAuthSession } from '../auth-control'
import type { AgentRun } from '@/lib/flux-repository'
import { classifyJob, filterJobs, getJobSummary, getPriorityJobs, type JobFilter, type JobWithStale } from '@/lib/jobs'
import styles from '../page.module.css'

const labels: Record<string, string> = { review: 'Em revisão', blocked: 'HOLD', in_progress: 'Em execução', completed: 'Concluído', awaiting_owner: 'HOLD · aguardando owner', failed: 'Falhou', planned: 'Planejado', ready: 'Planejado', not_verified: 'Não verificado' }
const lifecycle = (job: AgentRun) => classifyJob(job) === 'historical' ? 'Histórico' : classifyJob(job) === 'realtime' ? 'Em execução' : 'Planejado'
const short = (value: string | undefined, fallback = 'não declarado') => value?.trim() || fallback
const progress = (job: AgentRun) => Math.max(0, Math.min(100, job.progress ?? (job.status === 'completed' ? 100 : job.status === 'review' ? 75 : job.status === 'in_progress' ? 40 : 0)))

export default function JobsClient({ initial }: { initial: AgentRun[] }) {
  const [filter, setFilter] = useState<JobFilter>({}), [selected, setSelected] = useState<JobWithStale | null>(null), [message, setMessage] = useState('')
  const { session } = useAuthSession(); const visible = useMemo(() => filterJobs(initial, filter), [initial, filter]); const summary = useMemo(() => getJobSummary(initial), [initial]); const priority = useMemo(() => getPriorityJobs(visible), [visible])
  const values = (key: keyof JobFilter) => [...new Set(initial.map((job) => key === 'origin' ? (job.sourceType === 'filesystem' ? 'filesystem' : 'local') : key === 'lifecycle' ? (classifyJob(job) === 'historical' ? 'historical' : classifyJob(job) === 'realtime' ? 'live' : 'planned') : key === 'project' ? job.project : key === 'card' ? job.cardId : key === 'agent' ? job.agent : key === 'status' ? job.status : job.owner || '').filter(Boolean))]
  function set(key: keyof JobFilter, value: string) { setFilter((current) => ({ ...current, [key]: value || undefined })) }
  async function update(event: 'progress' | 'waiting_input', job: JobWithStale) { setMessage('Salvando readback…'); try { const response = await fetch(`/api/flux/jobs/${job.jobId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ event, nextStep: job.nextStep, owner: job.owner, currentStep: job.currentStep }) }); const result = await response.json().catch(() => ({})); setMessage(response.ok ? 'Registro local atualizado; nenhuma conclusão foi presumida.' : `${result.error || 'Erro'}: ${result.message || 'não foi possível registrar'}`) } catch { setMessage('Não foi possível conectar ao serviço.') } }
  return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>FBR Agency / Control Tower</p><h1>Jobs</h1><p className={styles.subtitle}>Visão executiva: situação, progresso, dependências e próxima ação. O JSON técnico fica nos detalhes.</p></div><nav><Link href="/">Dashboard</Link> · <Link href="/handoffs">Handoffs</Link></nav></header>
    <section className={styles.metrics}>{[['Total', summary.total], ['Planejados', summary.planned], ['Em execução', summary.realtime], ['HOLD', (summary.byStatus.blocked || 0) + (summary.byStatus.awaiting_owner || 0)], ['Concluídos', summary.byStatus.completed || 0], ['Histórico', summary.historical], ['Stale', summary.stale], ['Blockers ativos', summary.activeBlocker]].map(([label, value]) => <div className={styles.metric} key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <section className={styles.panel}><div className={styles.panelHeader}><h2>Filtrar jobs</h2></div><div className={styles.toolbar}>{(['project', 'card', 'agent', 'status', 'owner'] as const).map((key) => <label key={key}>{key === 'project' ? 'Projeto' : key === 'card' ? 'Card' : key === 'agent' ? 'Agente' : key === 'owner' ? 'Owner' : 'Status'}<select aria-label={key} value={String(filter[key] || '')} onChange={(event) => set(key, event.target.value)}><option value="">Todos</option>{values(key).map((value) => <option key={value} value={value}>{key === 'status' ? labels[value] || value : value}</option>)}</select></label>)}<label>Classificação<select aria-label="classificação" value={filter.lifecycle || ''} onChange={(event) => set('lifecycle', event.target.value)}><option value="">Todos</option><option value="planned">Planejado</option><option value="historical">Histórico</option><option value="live">Em execução</option></select></label><button type="button" onClick={() => setFilter({})}>Limpar</button></div></section>
    {message && <div role="status" className={styles.notice}>{message}</div>}{!session && <div className={styles.notice}>Leitura permitida; gestão bloqueada sem sessão.</div>}
    <section className={styles.panel}><div className={styles.panelHeader}><h2>Prioridade operacional <span className={styles.muted}>(máx. 6)</span></h2></div><div className={styles.cardGrid}>{priority.map((job) => <JobCard key={job.jobId} job={job} onClick={() => setSelected(job)} />)}</div></section>
    <section className={styles.panel}><div className={styles.panelHeader}><h2>Todos os jobs <span className={styles.muted}>({visible.length})</span></h2></div><div className={styles.jobList}>{visible.map((job) => <button className={styles.jobRow} type="button" key={job.jobId} onClick={() => setSelected(job)}><span><strong>{job.agent || 'agente não declarado'}</strong><small>{short(job.objective, 'objetivo não declarado')}</small></span><span>{job.project} / {job.cardId}<small>{short(job.currentStep, 'etapa não declarada')}</small></span><span><Status value={job.status} /><small>{lifecycle(job)}</small></span><span><Progress value={progress(job)} /><small>Última atividade: {job.lastActivity || job.lastSeen || job.updatedAt}</small></span></button>)}</div></section>
    {selected && <JobDetails job={selected} session={Boolean(session)} close={() => setSelected(null)} update={update} />}
  </main>
}
function JobDetails({ job, session, close, update }: { job: JobWithStale; session: boolean; close: () => void; update: (event: 'progress' | 'waiting_input', job: JobWithStale) => void }) { return <section className={styles.panel} role="dialog" aria-modal="true" aria-label="detalhes do job"><div className={styles.row}><h2>{job.agent}: {short(job.objective)}</h2><button type="button" onClick={close}>Fechar</button></div><p><Status value={job.status} /> · {lifecycle(job)} · {job.stale ? 'stale' : 'heartbeat atual'} · última atividade: {job.lastActivity || job.lastSeen || job.updatedAt}</p><div className={styles.executiveDetails}><p><strong>Etapa:</strong> {short(job.currentStep)}</p><p><strong>Progresso:</strong> {progress(job)}%</p><p><strong>Dependências:</strong> {(job.dependsOn || []).join(', ') || 'Nenhuma declarada'}</p><p><strong>Próxima ação:</strong> {short(job.nextStep)}</p><p><strong>Owner:</strong> {short(job.owner)}</p><p><strong>Evidências:</strong> {job.evidenceRefs.join(', ') || 'Nenhuma registrada'}</p></div><details className={styles.technicalDetails}><summary>Ver JSON técnico / readback</summary><pre>{JSON.stringify(job, null, 2)}</pre></details><div className={styles.actions}><button onClick={() => update('progress', job)} disabled={!session || !job.nextStep}>Registrar progresso / readback</button><button onClick={() => update('waiting_input', job)} disabled={!session || !job.activeBlocker || !job.owner || !job.nextStep}>Encaminhar para owner</button><button onClick={() => update('progress', job)} disabled={!session || !job.historical || !job.nextStep || !job.owner}>Retomar evolução</button></div><small role="note">Ações preservam o status real e não marcam conclusão sem evidência.</small></section> }
function JobCard({ job, onClick }: { job: JobWithStale; onClick: () => void }) { return <button className={styles.card} type="button" onClick={onClick}><span className={styles.cardId}>{job.agent} · {job.cardId}</span><h3>{short(job.objective)}</h3><Status value={job.status} /><Progress value={progress(job)} /><p>{lifecycle(job)} · {job.owner || 'owner não declarado'}</p></button> }
function Progress({ value }: { value: number }) { return <span className={styles.progressBar} aria-label={`Progresso ${value}%`}><span style={{ width: `${value}%` }} /></span> }
function Status({ value }: { value: string }) { return <span className={`${styles.status} ${styles[`status_${value}`] || ''}`}>{labels[value] || value}</span> }
