'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import type { AgentRun } from '@/lib/flux-repository'
import { filterJobs, getJobSummary, getPriorityJobs, type JobFilter, type JobWithStale } from '@/lib/jobs'
import styles from '../page.module.css'

const labels: Record<string, string> = { review: 'Review', blocked: 'Blocked', in_progress: 'Em evolução', completed: 'Concluído', awaiting_owner: 'Aguardando owner', failed: 'Falhou', planned: 'Planejado', not_verified: 'Não verificado' }
const origin = (job: AgentRun) => job.sourceType === 'filesystem' || job.source.toLowerCase().includes('filesystem') ? 'filesystem' : 'local'
const lifecycle = (job: AgentRun) => job.historical ? 'Histórico' : 'Realtime'
const short = (value: string | undefined, fallback = 'não declarado') => value?.trim() || fallback

export default function JobsClient({ initial }: { initial: AgentRun[] }) {
  const [filter, setFilter] = useState<JobFilter>({}), [selected, setSelected] = useState<JobWithStale | null>(null), [message, setMessage] = useState('')
  const visible = useMemo(() => filterJobs(initial, filter), [initial, filter]); const summary = useMemo(() => getJobSummary(initial), [initial]); const priority = useMemo(() => getPriorityJobs(visible), [visible])
  const values = (key: keyof JobFilter) => [...new Set(initial.map((j) => { if (key === 'origin') return j.sourceType || 'local'; if (key === 'lifecycle') return j.historical ? 'historical' : 'live'; if (key === 'project') return j.project; if (key === 'card') return j.cardId; if (key === 'agent') return j.agent; if (key === 'status') return j.status; if (key === 'owner') return j.owner || ''; return '' }).filter(Boolean))]
  function set(key: keyof JobFilter, value: string) { setFilter((current) => ({ ...current, [key]: value || undefined })) }
  async function update(event: 'progress' | 'waiting_input', job: JobWithStale) {
    const body = { event, nextStep: job.nextStep, owner: job.owner, currentStep: job.currentStep }
    const response = await fetch(`/api/flux/jobs/${job.jobId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json()
    setMessage(response.ok ? 'Registro local atualizado; nenhuma conclusão foi presumida.' : `${result.error || 'Erro'}: ${result.message || 'não foi possível registrar'}`)
  }
  return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>FBR Agency / Control Tower</p><h1>Jobs</h1><p className={styles.subtitle}>Readback operacional: histórico de filesystem separado de execução realtime.</p></div><nav><Link href="/">Dashboard</Link> · <Link href="/handoffs">Handoffs</Link></nav></header>
    <section className={styles.metrics}>{[['Total', summary.total], ['Review', summary.byStatus.review || 0], ['Blocked', summary.byStatus.blocked || 0], ['Histórico', summary.historical], ['Realtime', summary.live], ['Stale', summary.stale], ['Blockers ativos', summary.activeBlocker]].map(([label, value]) => <div className={styles.metric} key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <section className={styles.panel}><div className={styles.panelHeader}><h2>Filtros</h2></div><div className={styles.toolbar}>{(['project','card','agent','status','owner','origin'] as const).map((key) => <label key={key}>{key}<select aria-label={key} value={String(filter[key] || '')} onChange={(e) => set(key, e.target.value)}><option value="">Todos</option>{values(key).map((value) => <option key={value} value={value}>{key === 'status' ? labels[value] || value : value}</option>)}</select></label>)}<label>histórico/live<select aria-label="histórico/live" value={filter.lifecycle || ''} onChange={(e) => set('lifecycle', e.target.value)}><option value="">Todos</option><option value="historical">Histórico</option><option value="live">Realtime</option></select></label><label>stale<select aria-label="stale" value={filter.stale === undefined ? '' : String(filter.stale)} onChange={(e) => setFilter({ ...filter, stale: e.target.value === '' ? undefined : e.target.value === 'true' })}><option value="">Todos</option><option value="true">Stale</option><option value="false">Atual</option></select></label><label>blocker<select aria-label="blocker" value={filter.blocker === undefined ? '' : String(filter.blocker)} onChange={(e) => setFilter({ ...filter, blocker: e.target.value === '' ? undefined : e.target.value === 'true' })}><option value="">Todos</option><option value="true">Ativo</option><option value="false">Sem blocker</option></select></label><button onClick={() => setFilter({})}>Limpar</button></div></section>
    {message && <div role="status" className={styles.notice}>{message}</div>}
    <section className={styles.panel}><div className={styles.panelHeader}><h2>Prioridade operacional <span className={styles.muted}>(máx. 6)</span></h2></div><div className={styles.cardGrid}>{priority.map((job) => <JobCard key={job.jobId} job={job} onClick={() => setSelected(job)} />)}</div></section>
    <section className={styles.panel}><div className={styles.panelHeader}><h2>Todos os jobs <span className={styles.muted}>({visible.length})</span></h2></div><div className={styles.jobList}>{visible.map((job) => <button className={styles.jobRow} key={job.jobId} onClick={() => setSelected(job)}><span><strong>{job.agent || 'agent não declarado'}</strong><small>{short(job.objective, 'objetivo não declarado')}</small></span><span>{job.project} / {job.cardId}</span><Status value={job.status}/><span>{new Date(job.updatedAt).toLocaleString('pt-BR')}<small>{origin(job) === 'filesystem' ? 'filesystem readback' : 'realtime'}</small></span></button>)}</div></section>
    {selected && <section className={styles.panel} role="dialog" aria-label="detalhes do job"><div className={styles.row}><h2>{selected.agent}: {short(selected.objective)}</h2><button onClick={() => setSelected(null)}>Fechar</button></div><p><Status value={selected.status}/> · <strong>{selected.stale ? 'stale' : 'atual'}</strong> · <strong>{lifecycle(selected)}</strong> · <strong>{origin(selected) === 'filesystem' ? 'filesystem readback' : 'realtime'}</strong></p><div className={styles.detailGrid}>{[['Objetivo', selected.objective], ['Role', selected.role], ['Projeto/card', `${selected.project} / ${selected.cardId}`], ['Owner', short(selected.owner)], ['Started', short(selected.startedAt)], ['Updated', selected.updatedAt], ['Last seen', short(selected.lastSeen)], ['Progresso', selected.progress === undefined ? 'não declarado' : `${selected.progress}%`], ['Current step', short(selected.currentStep)], ['Artefatos', selected.artifactRefs.join(', ')], ['Evidências', selected.evidenceRefs.join(', ')], ['Handoffs relacionados', selected.handoffRefs.join(', ')], ['Riscos/pendências históricas', selected.blockers.join('; ')], ['Blockers ativos', selected.activeBlocker ? selected.blockers.join('; ') : 'nenhum'], ['Next step', short(selected.nextStep)], ['Correlation ID', selected.correlationId], ['Source', selected.source]].map(([key, value]) => <div key={key}><small>{key}</small><p>{short(String(value))}</p></div>)}</div><div className={styles.actions}><button onClick={() => update('progress', selected)} disabled={!selected.historical || !selected.nextStep || !selected.owner}>Retomar evolução</button><button onClick={() => update('waiting_input', selected)} disabled={!selected.activeBlocker || !selected.owner || !selected.nextStep}>Encaminhar para owner</button><button onClick={() => update('progress', selected)}>Registrar progresso / readback</button></div><small role="note">Ações preservam o status real, usam owner/nextStep declarados e não marcam conclusão sem evidência.</small></section>}
  </main>
}
function JobCard({ job, onClick }: { job: JobWithStale; onClick: () => void }) { return <button className={styles.card} onClick={onClick}><span className={styles.cardId}>{job.agent} · {job.cardId}</span><h3>{short(job.objective)}</h3><Status value={job.status}/><p>{job.stale ? 'stale · ' : ''}{lifecycle(job)} · {origin(job) === 'filesystem' ? 'filesystem readback' : 'realtime'}</p></button> }
function Status({ value }: { value: string }) { return <span className={`${styles.status} ${styles[`status_${value}`] || ''}`}>{labels[value] || value}</span> }
