-- 004: relational runtime completion for 003; no data deletion/backfill and no snapshot storage.
-- JSONB exists ONLY as RPC transport/local variables, never as a persisted column.
-- Execute with a migration owner; RPC execute is restricted to service_role.
BEGIN;
CREATE TABLE IF NOT EXISTS flux_runtime_revision (id boolean PRIMARY KEY DEFAULT true CHECK(id), version bigint NOT NULL DEFAULT 0, coordinator_waiting_reasons text[]);
INSERT INTO flux_runtime_revision(id) VALUES(true) ON CONFLICT DO NOTHING;
ALTER TABLE flux_tenants ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES flux_tenants(id) ON DELETE RESTRICT;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS tenant_id_external_ref text;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS owner_name text;
ALTER TABLE flux_projects ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES flux_projects(id) ON DELETE RESTRICT;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS project_id_external_ref text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES flux_tenants(id) ON DELETE RESTRICT;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS tenant_id_external_ref text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS assignee text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS priority text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS objective text;
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS criteria_values text[];
ALTER TABLE flux_cards ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES flux_tenants(id) ON DELETE RESTRICT;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS tenant_id_external_ref text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS requested_by text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS impact text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS action_scope text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS rollback_plan text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS decision text;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS decided_at timestamptz;
ALTER TABLE flux_approvals ADD COLUMN IF NOT EXISTS decided_by text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES flux_projects(id) ON DELETE RESTRICT;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS project_id_external_ref text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS required_decision text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS impact text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS cost text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS scope text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS reversibility text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS rollback_plan text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS evidence_refs text[];
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS requested_at timestamptz;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS decided_at timestamptz;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS decided_by text;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS external_action_authorized boolean;
ALTER TABLE flux_gates ADD COLUMN IF NOT EXISTS blocker_refs text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES flux_projects(id) ON DELETE RESTRICT;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS project_id_external_ref text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES flux_tenants(id) ON DELETE RESTRICT;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS tenant_id_external_ref text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS agent_name text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS objective text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS artifact_refs text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS handoff_refs text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS evidence_refs text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS blockers text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS next_step text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS correlation_ref text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS source_ref text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS domain_source_type text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS historical boolean;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS active_blocker boolean;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS last_activity text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS next_check_label text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS progress integer;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS current_step text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS last_event text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS verification_status text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS depends_on text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS blocks text[];
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS can_start boolean;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS parallel_group text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS track text;
ALTER TABLE flux_jobs ADD COLUMN IF NOT EXISTS dependency_reason text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES flux_projects(id) ON DELETE RESTRICT;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS project_id_external_ref text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS from_actor text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS to_actor text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS done text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS decisions text[];
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS risks text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS next_step text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS next_check_label text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS last_activity text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS acceptance_criteria text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS evidence_ref text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS last_update text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS last_blocker text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS last_release text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS blocker_id text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS job_id uuid REFERENCES flux_jobs(id) ON DELETE RESTRICT;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS job_id_external_ref text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS correlation_ref text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS forwarding_key text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS source_type text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS historical boolean;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS legacy boolean;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS source_ref text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS active_blocker boolean;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_present boolean;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_from text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_to text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_objective text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_deliverable text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_acceptance_criteria text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_evidence_required text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_next_step text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS resolution_action_fallback text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_present boolean;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_from text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_to text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_objective text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_deliverable text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_acceptance_criteria text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_evidence_required text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_next_step text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_fallback text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_actor text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_type text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_status text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_decision text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS interaction_message text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS solution_present boolean;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS solution_cause text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS solution_owner text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS solution_next_action text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS solution_resolution_plan text;
ALTER TABLE flux_handoffs ADD COLUMN IF NOT EXISTS solution_resolution_evidence text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS artifact_type text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS path_or_ref text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS source_path text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS size bigint;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS content_text text;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS content_binary bytea;
ALTER TABLE flux_artifacts ADD COLUMN IF NOT EXISTS content_type text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS source_id text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS cause text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS author text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS next_action text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_plan text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_evidence text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS verification_status text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_present boolean;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_from text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_to text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_objective text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_deliverable text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_acceptance_criteria text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_evidence_required text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_next_step text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS resolution_action_fallback text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES flux_projects(id) ON DELETE RESTRICT;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS project_id_external_ref text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES flux_tenants(id) ON DELETE RESTRICT;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS tenant_id_external_ref text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS objective text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS starts_at timestamptz;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS ends_at timestamptz;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS dependencies text[];
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS next_check_label text;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE flux_sprints ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS sprint_id uuid REFERENCES flux_sprints(id) ON DELETE RESTRICT;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS sprint_id_external_ref text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES flux_projects(id) ON DELETE RESTRICT;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS project_id_external_ref text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES flux_tenants(id) ON DELETE RESTRICT;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS tenant_id_external_ref text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS objective text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS criteria_values text[];
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS card_ids text[];
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS job_ids text[];
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS evidence_refs text[];
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS blocker_ids text[];
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS next_check_label text;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE flux_stories ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS dedupe_key text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS what text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS why text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS who text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS from_actor text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS to_actor text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS objective text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS deliverable text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS acceptance_criteria text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS due_check_label text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS fallback text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS reason_code text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS correlation_ref text;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE flux_required_actions ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS heartbeat_at timestamptz;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS last_activity_at timestamptz;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS idle_detected integer;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS dispatched integer;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS holds integer;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS required_actions integer;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS waiting_reasons text[];
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS result text;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS last_check_label text;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS next_follow_up_label text;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS unanswered integer;
ALTER TABLE flux_coordinator_runs ADD COLUMN IF NOT EXISTS backlog_actionable integer;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS correlation_ref text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS operation text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS actor text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS job_id uuid REFERENCES flux_jobs(id) ON DELETE RESTRICT;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS job_id_external_ref text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS duration_ms integer;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_present boolean;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_card_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_from_status text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_status text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_approval_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_decision text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_gate_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_handoff_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_blocker_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_artifact_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_project_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_tenant text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_event_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_type text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_sprint_id text;
ALTER TABLE flux_receipts ADD COLUMN IF NOT EXISTS metadata_story_id text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS external_id text UNIQUE;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS ordinal bigint;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS actor text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS card_id uuid REFERENCES flux_cards(id) ON DELETE RESTRICT;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS card_id_external_ref text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS correlation_ref text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS from_status text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS to_status text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS blocker_id text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS job_id uuid REFERENCES flux_jobs(id) ON DELETE RESTRICT;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS job_id_external_ref text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS handoff_id uuid REFERENCES flux_handoffs(id) ON DELETE RESTRICT;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS handoff_id_external_ref text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS from_actor text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS to_actor text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS next_action text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS receipt_id uuid REFERENCES flux_receipts(id) ON DELETE RESTRICT;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS receipt_id_external_ref text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS solution_present boolean;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS solution_cause text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS solution_owner text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS solution_next_action text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS solution_resolution_plan text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS solution_resolution_evidence text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_present boolean;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_from text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_to text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_objective text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_deliverable text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_acceptance_criteria text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_evidence_required text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_next_step text;
ALTER TABLE flux_events ADD COLUMN IF NOT EXISTS resolution_action_fallback text;
ALTER TABLE flux_blockers ADD COLUMN IF NOT EXISTS container_handoff_id uuid REFERENCES flux_handoffs(id) ON DELETE RESTRICT;
-- Domain has no mandatory tenant/project on global coordinator/actions/events/receipts,
-- and partial legacy blocker input is explicitly representable (never fabricated).
ALTER TABLE flux_cards DROP CONSTRAINT IF EXISTS flux_cards_status_check;
ALTER TABLE flux_cards ADD CONSTRAINT flux_cards_status_check CHECK(status IN ('planned','ready','in_progress','review','blocked','awaiting_owner','awaiting_approval','approved','executing','verifying','completed','failed'));
ALTER TABLE flux_receipts DROP CONSTRAINT IF EXISTS flux_receipts_status_check;
ALTER TABLE flux_receipts ADD CONSTRAINT flux_receipts_status_check CHECK(status IN ('started','completed','failed','blocked','rejected'));
ALTER TABLE flux_artifacts DROP CONSTRAINT IF EXISTS flux_artifact_content_exclusive;
ALTER TABLE flux_artifacts ADD CONSTRAINT flux_artifact_content_exclusive CHECK(content_text IS NULL OR content_binary IS NULL);

ALTER TABLE flux_sprints ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_sprints ALTER COLUMN next_check DROP NOT NULL;
ALTER TABLE flux_stories ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_stories ALTER COLUMN next_check DROP NOT NULL;
ALTER TABLE flux_jobs ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_jobs ALTER COLUMN correlation_id DROP NOT NULL;
ALTER TABLE flux_gates ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_required_actions ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_required_actions ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE flux_required_actions ALTER COLUMN due_check DROP NOT NULL;
ALTER TABLE flux_required_actions ALTER COLUMN correlation_id DROP NOT NULL;
ALTER TABLE flux_coordinator_runs ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_coordinator_runs ALTER COLUMN correlation_id DROP NOT NULL;
ALTER TABLE flux_receipts ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_receipts ALTER COLUMN correlation_id DROP NOT NULL;
ALTER TABLE flux_receipts ALTER COLUMN actor DROP NOT NULL;
ALTER TABLE flux_events ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN owner DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN next_action DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN resolution_plan DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN status DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN resolution DROP NOT NULL;
ALTER TABLE flux_blockers ALTER COLUMN verification_status DROP NOT NULL;
CREATE OR REPLACE FUNCTION flux_relational_read() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE result jsonb; t text; items jsonb;
BEGIN
  SELECT jsonb_build_object('version',version,'waitingReasons',coordinator_waiting_reasons) INTO result FROM public.flux_runtime_revision WHERE id=true;
  FOREACH t IN ARRAY ARRAY['flux_projects','flux_cards','flux_approvals','flux_gates','flux_jobs','flux_handoffs','flux_artifacts','flux_blockers','flux_sprints','flux_stories','flux_required_actions','flux_coordinator_runs','flux_receipts','flux_events','flux_tenants'] LOOP
    EXECUTE format('SELECT coalesce(jsonb_agg(to_jsonb(r)), ''[]''::jsonb) FROM public.%I r',t) INTO items;
    result := result || jsonb_build_object(t,items);
  END LOOP;
  RETURN result;
END $$;
CREATE OR REPLACE FUNCTION flux_relational_commit(expected_version bigint, changes jsonb, waiting_reasons text[] DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE current_version bigint; item jsonb; t text; c text; allowed text[]; cols text; vals text; updates text;
BEGIN
  SELECT version INTO current_version FROM public.flux_runtime_revision WHERE id=true FOR UPDATE;
  IF expected_version IS DISTINCT FROM current_version THEN RAISE EXCEPTION 'PERSISTENCE_CONFLICT' USING ERRCODE='40001'; END IF;
  IF jsonb_typeof(changes) <> 'array' THEN RAISE EXCEPTION 'INVALID_RELATIONAL_CHANGES'; END IF;
  FOR item IN SELECT value FROM jsonb_array_elements(changes) LOOP
    t := item->>'table';
    allowed := CASE t WHEN 'flux_projects' THEN ARRAY['id','external_id','ordinal','name','tenant_id','tenant_id_external_ref','status','owner_name','description','slug']::text[]
WHEN 'flux_cards' THEN ARRAY['id','external_id','ordinal','project_id','project_id_external_ref','tenant_id','tenant_id_external_ref','title','status','assignee','priority','objective','criteria_values','updated_at','acceptance_criteria']::text[]
WHEN 'flux_approvals' THEN ARRAY['id','external_id','ordinal','card_id','card_id_external_ref','tenant_id','tenant_id_external_ref','title','requested_by','impact','action_scope','rollback_plan','decision','decided_at','decided_by']::text[]
WHEN 'flux_gates' THEN ARRAY['id','external_id','ordinal','card_id','card_id_external_ref','project_id','project_id_external_ref','title','required_decision','status','impact','cost','scope','reversibility','rollback_plan','evidence_refs','owner','requested_at','decided_at','decided_by','external_action_authorized','blocker_refs','tenant_id']::text[]
WHEN 'flux_jobs' THEN ARRAY['id','external_id','ordinal','card_id','card_id_external_ref','project_id','project_id_external_ref','tenant_id','tenant_id_external_ref','agent_name','role','objective','status','started_at','updated_at','completed_at','artifact_refs','handoff_refs','evidence_refs','blockers','next_step','correlation_ref','source_ref','domain_source_type','historical','active_blocker','last_seen_at','last_activity','next_check_label','progress','current_step','owner','last_event','verification_status','depends_on','blocks','can_start','parallel_group','track','dependency_reason']::text[]
WHEN 'flux_handoffs' THEN ARRAY['id','external_id','ordinal','card_id','card_id_external_ref','project_id','project_id_external_ref','from_actor','to_actor','summary','done','decisions','risks','next_step','next_check_label','last_activity','acceptance_criteria','evidence_ref','created_at','status','last_update','last_blocker','last_release','blocker_id','job_id','job_id_external_ref','correlation_ref','forwarding_key','source_type','historical','legacy','source_ref','active_blocker','resolution_action_present','resolution_action_from','resolution_action_to','resolution_action_objective','resolution_action_deliverable','resolution_action_acceptance_criteria','resolution_action_evidence_required','resolution_action_next_step','resolution_action_fallback','interaction_present','interaction_from','interaction_to','interaction_objective','interaction_deliverable','interaction_acceptance_criteria','interaction_evidence_required','interaction_next_step','interaction_fallback','interaction_actor','interaction_type','interaction_status','interaction_decision','interaction_message','solution_present','solution_cause','solution_owner','solution_next_action','solution_resolution_plan','solution_resolution_evidence','tenant_id']::text[]
WHEN 'flux_artifacts' THEN ARRAY['id','external_id','ordinal','card_id','card_id_external_ref','name','artifact_type','status','path_or_ref','source_path','size','content_text','content_binary','content_type','tenant_id','project_id']::text[]
WHEN 'flux_blockers' THEN ARRAY['id','external_id','ordinal','source_id','card_id','card_id_external_ref','cause','status','owner','author','next_action','resolution_plan','resolution_evidence','resolution','verification_status','resolution_action_present','resolution_action_from','resolution_action_to','resolution_action_objective','resolution_action_deliverable','resolution_action_acceptance_criteria','resolution_action_evidence_required','resolution_action_next_step','resolution_action_fallback','tenant_id','project_id','container_handoff_id']::text[]
WHEN 'flux_sprints' THEN ARRAY['id','external_id','ordinal','project_id','project_id_external_ref','tenant_id','tenant_id_external_ref','name','objective','status','owner','starts_at','ends_at','dependencies','next_check_label','created_at','updated_at']::text[]
WHEN 'flux_stories' THEN ARRAY['id','external_id','ordinal','sprint_id','sprint_id_external_ref','project_id','project_id_external_ref','tenant_id','tenant_id_external_ref','title','objective','owner','criteria_values','status','card_ids','job_ids','evidence_refs','blocker_ids','next_check_label','created_at','updated_at']::text[]
WHEN 'flux_required_actions' THEN ARRAY['id','external_id','ordinal','dedupe_key','what','why','who','from_actor','to_actor','objective','deliverable','acceptance_criteria','due_check_label','fallback','status','reason_code','correlation_ref','created_at','updated_at','tenant_id','project_id']::text[]
WHEN 'flux_coordinator_runs' THEN ARRAY['id','external_id','ordinal','started_at','completed_at','heartbeat_at','last_activity_at','idle_detected','dispatched','holds','required_actions','waiting_reasons','result','last_check_label','next_follow_up_label','unanswered','backlog_actionable','tenant_id']::text[]
WHEN 'flux_receipts' THEN ARRAY['id','external_id','ordinal','correlation_ref','operation','status','actor','job_id','job_id_external_ref','started_at','completed_at','duration_ms','metadata_present','metadata_card_id','metadata_from_status','metadata_status','metadata_approval_id','metadata_decision','metadata_gate_id','metadata_handoff_id','metadata_blocker_id','metadata_artifact_id','metadata_project_id','metadata_tenant','metadata_event_id','metadata_type','metadata_sprint_id','metadata_story_id','tenant_id']::text[]
WHEN 'flux_events' THEN ARRAY['id','external_id','ordinal','created_at','actor','event_type','card_id','card_id_external_ref','correlation_ref','from_status','to_status','reason','blocker_id','job_id','job_id_external_ref','handoff_id','handoff_id_external_ref','from_actor','to_actor','owner','next_action','receipt_id','receipt_id_external_ref','solution_present','solution_cause','solution_owner','solution_next_action','solution_resolution_plan','solution_resolution_evidence','resolution_action_present','resolution_action_from','resolution_action_to','resolution_action_objective','resolution_action_deliverable','resolution_action_acceptance_criteria','resolution_action_evidence_required','resolution_action_next_step','resolution_action_fallback','tenant_id','project_id']::text[] ELSE NULL END;
    IF allowed IS NULL OR jsonb_typeof(item->'row') <> 'object' OR item->'row'->>'id' IS NULL THEN RAISE EXCEPTION 'INVALID_RELATIONAL_TABLE_OR_ROW'; END IF;
    cols := ''; vals := ''; updates := '';
    FOR c IN SELECT jsonb_object_keys(item->'row') LOOP
      IF NOT c=ANY(allowed) THEN RAISE EXCEPTION 'INVALID_RELATIONAL_COLUMN'; END IF;
      cols := cols || format('%I,',c); vals := vals || format('r.%I,',c);
      IF c <> 'id' THEN updates := updates || format('%I=EXCLUDED.%I,',c,c); END IF;
    END LOOP;
    IF item->>'operation' IS DISTINCT FROM 'upsert' THEN RAISE EXCEPTION 'DELETION_NOT_SUPPORTED'; END IF;
    EXECUTE format('INSERT INTO public.%I (%s) SELECT %s FROM jsonb_populate_record(NULL::public.%I,$1) r ON CONFLICT(id) DO UPDATE SET %s', t,rtrim(cols,','),rtrim(vals,','),t,rtrim(updates,',')) USING item->'row';
  END LOOP;
  UPDATE public.flux_runtime_revision SET version=version+1, coordinator_waiting_reasons=waiting_reasons WHERE id=true;
  RETURN public.flux_relational_read();
END $$;
REVOKE ALL ON FUNCTION flux_relational_read() FROM PUBLIC;
REVOKE ALL ON FUNCTION flux_relational_commit(bigint,jsonb,text[]) FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN
  GRANT EXECUTE ON FUNCTION flux_relational_read() TO service_role;
  GRANT EXECUTE ON FUNCTION flux_relational_commit(bigint,jsonb,text[]) TO service_role;
END IF; END $$;
ALTER TABLE flux_projects ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_projects FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_cards ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_cards FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_approvals ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_approvals FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_gates ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_gates FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_jobs ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_handoffs ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_handoffs FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_artifacts ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_artifacts FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_blockers ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_blockers FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_sprints ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_sprints FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_stories ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_stories FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_required_actions ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_required_actions FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_coordinator_runs ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_coordinator_runs FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_receipts ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_receipts FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_events ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_events FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_tenants ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE flux_runtime_revision ENABLE ROW LEVEL SECURITY; ALTER TABLE flux_runtime_revision FORCE ROW LEVEL SECURITY;
COMMIT;
