-- QUARANTINED LEGACY DRAFT — DO NOT APPLY.
--
-- This file previously generated Flux relational objects in public. It is retained
-- only as historical evidence. The canonical source is:
--   003_flux_relational_persistence.sql
--   004_flux_relational_rpcs.sql
-- Both canonical migrations own Flux objects under custom_agencyflux.
--
-- No executable SQL is intentionally present here. Any migration runner that
-- still references this path must be updated before a remote migration Gate.
