'use client'
import Link from 'next/link'
import type { DashboardSnapshot } from '../lib/flux-repository'
import { getJobSummary, getPriorityJobs } from '../lib/jobs'
import BlockerAttention from './blocker-attention'
import styles from './page.module.css'
const labels: Record<string,string>={pending:'Pendente',approved:'Aprovado',rejected:'Rejeitado',changes_requested:'Alteração solicitada',active:'Ativo',blocked:'Bloqueado',planned:'Planejado',review:'Review',awaiting_approval:'Aguardando aprovação',completed:'Concluído'}
export default function DashboardClient({initial}:{initial:DashboardSnapshot}) {
 const jobs=initial.jobs||[], jobSummary=getJobSummary(jobs), attention=initial.handoffs.filter(h=>h.status==='awaiting_owner').length+initial.blockers.length+jobSummary.stale
 return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>FBR Agency / Control Tower</p><h1>Agency Flux</h1><p className={styles.subtitle}>Resumo executivo persistido · sem efeito externo</p></div><nav><Link href="/handoffs">Handoffs</Link> · <Link href="/jobs">Jobs</Link></nav></header>
  <section className={styles.metrics}><Metric label="Gates pendentes" value={initial.pendingGates}/><Metric label="Cards ativos" value={initial.activeCards}/><Metric label="Atenção necessária" value={attention}/><Metric label="Jobs" value={jobSummary.total}/></section>
  <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHeader}><h2>Projetos e cards prioritários</h2></div>{initial.projects.slice(0,4).map(project=><div className={styles.project} key={project.id}><div className={styles.row}><strong>{project.name}</strong><Status value={project.status}/></div><p>{project.description}</p>{(initial.projectCards[project.name]||[]).filter(c=>c.priority==='high').slice(0,3).map(card=><div className={styles.compactItem} key={card.id}><strong>{card.id}</strong> {card.title}<Status value={card.status}/></div>)}</div>)}</section>
  <section className={styles.panel}><div className={styles.panelHeader}><h2>Gates pendentes/recentes</h2></div>{initial.gates.filter(g=>g.status==='pending'||g.decidedAt).slice(0,4).map(g=><div className={styles.compactItem} key={g.id}><span><strong>{g.id}</strong><small>{g.title}</small></span><Status value={g.status}/></div>)}{!initial.gates.length&&<p className={styles.muted}>Nenhum gate registrado.</p>}</section>
  <BlockerAttention blockers={initial.blockers} snapshot={initial}/><section className={styles.panel}><div className={styles.panelHeader}><h2>Atenção operacional</h2></div><p className={attention?styles.alertText:styles.muted}>{initial.handoffs.filter(h=>h.status==='awaiting_owner').length} Handoffs aguardando owner</p><p className={jobSummary.stale?styles.alertText:styles.muted}>{jobSummary.stale} jobs stale</p><p className={initial.requiredActions?.filter(a=>a.status==='hold').length?styles.alertText:styles.muted}>{initial.requiredActions?.filter(a=>a.status==='hold').length||0} ações em HOLD</p><p className={styles.muted}>{initial.coordinator?.lastCoordinatorRun ? `Último ciclo: ${new Date(initial.coordinator.lastCoordinatorRun.completedAt).toLocaleString('pt-BR')}` : 'Íris ainda não executou ciclo'}</p>{(initial.coordinator?.waitingReasons||[]).slice(0,2).map(reason=><p className={styles.muted} key={reason}>Espera: {reason}</p>)}<div className={styles.actions}><Link href="/handoffs">Tratar Handoffs</Link><Link href="/jobs">Tratar Jobs</Link></div></section>
  <section className={`${styles.panel} ${styles.wide}`}><div className={styles.panelHeader}><h2>Últimos 5 eventos</h2></div><ul className={styles.events}>{initial.recentEvents.slice(0,5).map(event=><li key={event.id}><span className={styles.eventDot}/><span>{event.action}<small>{event.actor} · {new Date(event.time).toLocaleString('pt-BR')}</small></span></li>)}</ul></section></div><footer>Resumo limitado a prioridades; detalhes operacionais ficam em Handoffs e Jobs.</footer></main>
}
function Metric({label,value}:{label:string;value:number}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Status({value}:{value:string}){return <span className={`${styles.status} ${styles[`status_${value}`]||''}`}>{labels[value]||value}</span>}
