'use client'
import Link from 'next/link'
import type { DashboardSnapshot } from '../lib/flux-repository'
import styles from './page.module.css'
const labels: Record<string,string>={pending:'Pendente',approved:'Aprovado',rejected:'Rejeitado',changes_requested:'Alteração solicitada',active:'Ativo',blocked:'Bloqueado',planned:'Planejado',review:'Em revisão',awaiting_approval:'Aguardando aprovação',completed:'Concluído'}
export default function DashboardClient({initial}:{initial:DashboardSnapshot}) { const recent=initial.recentEvents.slice(0,5); return <main className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>FBR Agency / Control Tower</p><h1>Agency Flux</h1><p className={styles.subtitle}>Visão essencial do estado persistido · sem efeito externo</p></div><nav><Link href="/handoffs">Handoffs</Link> · <Link href="/api/flux/jobs">Jobs</Link></nav></header><section className={styles.metrics}><Metric label="Gates pendentes" value={initial.pendingGates}/><Metric label="Cards pendentes" value={initial.pendingCards}/><Metric label="Blockers" value={initial.blockerCount}/><Metric label="Projetos" value={initial.projects.length}/></section><div className={styles.grid}><Panel title="Projetos e cards"><div className={styles.projectList}>{initial.projects.map(p=><article className={styles.project} key={p.id}><div className={styles.row}><strong>{p.name}</strong><Status value={p.status}/></div><p>{p.description}</p><small>{initial.projectCards[p.name]?.length||0} card(s) · owner {p.owner}</small></article>)}</div></Panel><Panel title="Gates"><div className={styles.projectList}>{initial.gates.map(g=><article className={styles.project} key={g.id}><div className={styles.row}><strong>{g.title}</strong><Status value={g.status}/></div><small>{g.owner} · {g.cardId}</small></article>)}</div></Panel></div><section className={styles.panel}><div className={styles.panelHeader}><h2>Atividade recente</h2></div><ol className={styles.events}>{recent.map(e=><li key={e.id}><span className={styles.eventDot}/><div><strong>{e.actor}</strong> {e.action}<small>{e.time}</small></div></li>)}</ol><p className={styles.muted}>Detalhes operacionais e histórico completo em <a href="/handoffs">Handoffs</a>; execução acompanhada em <a href="/api/flux/jobs">Jobs</a>.</p></section><footer>Snapshot não equivale ao histórico completo. Nenhuma ação externa.</footer></main> }
function Metric({label,value}:{label:string;value:number}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className={styles.panel}><div className={styles.panelHeader}><h2>{title}</h2></div>{children}</section>}
function Status({value}:{value:string}){return <span className={`${styles.status} ${styles[`status_${value}`]||''}`}>{labels[value]||value}</span>}
