import Link from 'next/link'
import type { ReactNode } from 'react'
import type { RecordFilters } from '../lib/ui-records'
import styles from './page.module.css'
export function Fields({ fields }: { fields: Array<[string, ReactNode]> }) { return <dl className={styles.fields}>{fields.map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value === undefined || value === null || value === '' ? 'Não declarado' : value}</dd></div>)}</dl> }
export function References({ values, kind }: {values?: string[];kind?: 'job'|'handoff'|'card'|'blocker'}) { return values?.length ? <ul>{values.map((value,index) => <li key={`${value}-${index}`}>{kind ? <Link href={`${kind === 'job' ? '/jobs' : kind === 'handoff' ? '/handoffs' : '/'}?${kind}=${encodeURIComponent(value)}`}>{value}</Link> : /^https?:\/\//i.test(value) ? <a href={value} target="_blank" rel="noopener noreferrer">{value}</a> : value}</li>)}</ul> : <>Nenhum registro declarado</> }
export function RecordFiltersForm({ filters, setFilters, owners, projects }: {filters:RecordFilters;setFilters:(filters:RecordFilters)=>void;owners:string[];projects:string[]}) {
 return <section className={styles.toolbar} aria-label="Filtros"><label>Owner<select value={filters.owner || ''} onChange={e=>setFilters({...filters,owner:e.target.value})}><option value="">Todos</option>{owners.map(v=><option key={v}>{v}</option>)}</select></label><label>Projeto<select value={filters.project || ''} onChange={e=>setFilters({...filters,project:e.target.value})}><option value="">Todos</option>{projects.map(v=><option key={v}>{v}</option>)}</select></label><label>Data inicial<input type="date" value={filters.from || ''} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Data final<input type="date" min={filters.from || undefined} value={filters.to || ''} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><button type="button" onClick={()=>setFilters({})}>Limpar filtros</button>{filters.from && filters.to && filters.from > filters.to && <p role="alert">Data final deve ser igual ou posterior à inicial.</p>}<small>Intervalo inclusivo de última atualização, no horário local. Sem filtros, todos os registros são exibidos.</small></section>
}
