import Link from 'next/link'
import type { ReactNode } from 'react'
import type { DashboardSnapshot } from '@/lib/flux-repository'
import { isJobStale } from '@/lib/jobs'
import { queryValue, type PageQuery } from '@/lib/ui-records'
import { Fields, References } from './record-ui'
import styles from './page.module.css'
const ref=(kind:string,id?:string)=>id?<Link href={`${kind==='job'?'/jobs':kind==='handoff'?'/handoffs':'/'}?${kind}=${encodeURIComponent(id)}`}>{id}</Link>:'Não declarado'
export default function DashboardDetails({snapshot:s,query}:{snapshot:DashboardSnapshot;query:PageQuery}) {
 const kind=['project','card','gate','blocker','event','handoff','job','action','view'].find(k=>queryValue(query,k))
 if(!kind)return null
 const id=queryValue(query,kind)
 let title='Detalhes',fields:Array<[string,ReactNode]>=[],content:ReactNode=null,found=false
 if(kind==='project') {const p=s.projects.find(p=>p.id===id);if(p){found=true;title=p.name;fields=[['Owner',p.owner],['Status',p.status],['Escopo',p.description]];content=<><h3>Cards do projeto</h3><References values={s.cards.filter(c=>c.project===p.id||c.project===p.name).map(c=>c.id)} kind="card"/></>}}
 if(kind==='card') {const c=s.cards.find(c=>c.id===id);if(c){found=true;title=c.title;fields=[['Identificador',c.id],['Projeto',ref('project',s.projects.find(p=>p.id===c.project||p.name===c.project)?.id)],['Responsável',c.assignee],['Status',c.status],['Prioridade',c.priority],['Objetivo / detalhe',c.detail],['Critérios de aceite',<References key="criteria" values={c.acceptanceCriteria}/>],['Atualização',c.updatedAt]];content=<><h3>Jobs relacionados</h3><References values={s.jobs?.filter(j=>j.cardId===c.id).map(j=>j.jobId)} kind="job"/><h3>Handoffs relacionados</h3><References values={s.handoffs.filter(h=>h.cardId===c.id).map(h=>h.id)} kind="handoff"/><h3>Artefatos</h3><References values={s.artifacts.filter(a=>a.cardId===c.id).map(a=>a.path)}/></>}}
 if(kind==='gate') {const g=s.gates.find(g=>g.id===id);if(g){found=true;title=g.title;fields=[['Identificador',g.id],['Card',ref('card',g.cardId)],['Projeto',g.project],['Owner',g.owner],['Status',g.status],['Decisão requerida',g.requiredDecision],['Impacto',g.impact],['Custo',g.cost],['Escopo',g.scope],['Reversibilidade',g.reversibility],['Rollback',g.rollback],['Evidências',<References key="evidence" values={g.evidence}/>],['Blockers',<References key="blockers" values={g.blockers}/>],['Solicitado em',g.requestedAt],['Decidido em',g.decidedAt],['Decidido por',g.decidedBy],['Efeito externo','Não autorizado por esta decisão']]}}
 if(kind==='blocker') {const b=s.blockers.find(b=>b.id===id)||s.handoffs.flatMap(h=>h.blockers||[]).find(b=>b.id===id);if(b){found=true;title=b.cause;fields=[['Identificador',b.id],['Status',b.status],['Owner',b.owner],['Autor',b.author],['Card',ref('card',b.cardId)],['Origem',ref('handoff',b.sourceId)],['Próxima ação',b.nextAction],['Plano de resolução',b.resolutionPlan],['Evidência de resolução',b.resolutionEvidence],['Verificação',b.verification],['Objetivo',b.resolutionAction?.objective],['Entregável',b.resolutionAction?.deliverable],['Critérios',b.resolutionAction?.acceptanceCriteria],['Evidência necessária',b.resolutionAction?.evidenceRequired]]}}
 if(kind==='event') {const e=s.recentEvents.find(e=>e.id===id);if(e){found=true;title=e.action;fields=[['Identificador',e.id],['Data',e.time],['Actor',e.actor],['Motivo',e.reason],['Estado anterior',e.fromStatus],['Estado posterior',e.toStatus],['Card',ref('card',e.cardId)],['Job',ref('job',e.jobId)],['Handoff',ref('handoff',e.handoffId)],['Blocker',ref('blocker',e.blockerId)],['Owner',e.owner],['Próxima ação',e.nextAction],['Correlação',e.correlationId]];if(e.solution)fields.push(['Causa',e.solution.cause],['Plano de resolução',e.solution.resolutionPlan],['Evidência',e.solution.resolutionEvidence]);if(e.resolutionAction)fields.push(['Objetivo',e.resolutionAction.objective],['Entregável',e.resolutionAction.deliverable],['Critérios',e.resolutionAction.acceptanceCriteria])}}
 if(kind==='handoff'){const h=s.handoffs.find(h=>h.id===id);if(h){found=true;title=h.summary;fields=[['Owner',h.to],['De',h.from],['Status',h.status],['Feito',h.done],['Riscos',h.risks],['Próximo passo',h.nextStep],['Critérios de aceite',h.acceptanceCriteria],['Evidência',h.evidenceRef],['Card',ref('card',h.cardId)]];content=<Link href={`/handoffs?handoff=${encodeURIComponent(h.id)}&interact=true`}>Detalhes completos e interação</Link>}}
 if(kind==='job'){const j=s.jobs?.find(j=>j.jobId===id);if(j){found=true;title=j.objective;fields=[['Owner',j.owner||j.agent],['Status',j.status],['Etapa',j.currentStep],['Próxima ação',j.nextStep],['Evidências',<References key="evidence" values={j.evidenceRefs}/>]];content=<Link href={`/jobs?job=${encodeURIComponent(j.jobId)}`}>Detalhes completos do job</Link>}}
 if(kind==='action'){const a=s.requiredActions?.find(a=>a.id===id);if(a){found=true;title=a.what;fields=[['Motivo',a.why],['Owner',a.who],['De',a.from],['Para',a.to],['Objetivo',a.objective],['Entregável',a.deliverable],['Critérios',a.acceptanceCriteria],['Próximo check',a.dueCheck],['Fallback',a.fallback],['Status',a.status],['Motivo do HOLD',a.reasonCode],['Correlação',a.correlationId],['Atualização',a.updatedAt]]}}
 if(kind==='view'){
  const views:Record<string,string>={gates:'Gates pendentes',cards:'Cards ativos',attention:'Atenção necessária',actions:'Ações em HOLD',history:'Histórico de eventos',coordinator:'Coordenação'}
  if(views[id]){found=true;title=views[id];let entries:Array<{id:string;label:string;kind:string}>=[]
   if(id==='gates')entries=s.gates.filter(g=>g.status==='pending').map(g=>({id:g.id,label:g.title,kind:'gate'}))
   if(id==='cards')entries=s.cards.filter(c=>!['blocked','completed','failed'].includes(c.status)).map(c=>({id:c.id,label:c.title,kind:'card'}))
   if(id==='history')entries=s.recentEvents.map(e=>({id:e.id,label:`${e.action} · ${e.actor} · ${e.time}`,kind:'event'}))
   if(id==='actions')entries=(s.requiredActions||[]).filter(a=>a.status==='hold').map(a=>({id:a.id,label:a.what,kind:'action'}))
   if(id==='attention')entries=[...s.blockers.map(b=>({id:b.id,label:b.cause,kind:'blocker'})),...s.handoffs.filter(h=>h.status==='awaiting_owner').map(h=>({id:h.id,label:h.summary,kind:'handoff'})),...(s.jobs||[]).filter(j=>isJobStale(j,new Date())).map(j=>({id:j.jobId,label:j.objective,kind:'job'}))]
   content=entries.length?<ul className={styles.detailList}>{entries.map(e=><li key={`${e.kind}-${e.id}`}><Link href={`${e.kind==='job'?'/jobs':e.kind==='handoff'?'/handoffs':'/'}?${e.kind}=${encodeURIComponent(e.id)}`}>{e.label}</Link></li>)}</ul>:<p>Nenhum registro nesta seleção.</p>
   if(id==='coordinator'){const r=s.coordinator?.lastCoordinatorRun;content=r?null:<p>Nenhum ciclo registrado.</p>;if(r)fields=[['Correlação',r.correlationId],['Início',r.startedAt],['Fim',r.completedAt],['Heartbeat',r.heartbeat],['Última atividade',r.lastActivity],['Próximo check',r.nextFollowUp],['Resultado',r.result],['Dispatches registrados',r.dispatched],['HOLDs',r.holds],['Ações requeridas',r.requiredActions],['Motivos de espera',<References key="waiting" values={r.waitingReasons}/>]]}
  }
 }
 return <aside className={styles.detailOverlay} aria-label="Detalhes selecionados"><section className={styles.detailSheet}><div className={styles.row}><h2>{title}</h2><Link href="/" aria-label="Fechar detalhes">Fechar</Link></div>{found?<><Fields fields={fields}/>{content}</>:<p role="alert">Registro não encontrado no escopo autorizado.</p>}</section></aside>
}
