import { afterEach, describe, expect, it } from 'vitest'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { getSnapshot, normalizeHandoff, resumeHandoff, resumeLegacyHandoff, syncHandoffs, type FluxState, type Handoff } from '../src/lib/flux-repository'

const dirs: string[] = []
async function fixture() { const dir=await mkdtemp(join(tmpdir(),'handoffs-')); dirs.push(dir); const file=join(dir,'state.json'); const state=JSON.parse(await readFile(join(process.cwd(),'data/after-forty-intake.fixture.json'),'utf8')) as FluxState; state.handoffs=[{id:'local-handoff',cardId:'AF-001',project:'After Forty',from:'Íris',to:'Gabe',summary:'Revisar evidências',done:'',risks:'',nextStep:'revisar',acceptanceCriteria:'evidência',evidenceRef:'tests',createdAt:new Date().toISOString(),status:'received',solution:{cause:'revisão pendente',owner:'Gabe',nextAction:'revisar evidência',resolutionPlan:'comparar fontes',resolutionEvidence:'tests'}}]; await writeFile(file,JSON.stringify(state)); return file }
afterEach(async()=>{await Promise.all(dirs.splice(0).map(d=>rm(d,{recursive:true,force:true})) )})

describe('operational handoffs',()=>{
 it('normalizes status and operational timestamps without inventing details',()=>{const h=normalizeHandoff({id:'h',cardId:'c',project:'p',from:'a',to:'b',summary:'s',done:'',risks:'',nextStep:'',acceptanceCriteria:'',evidenceRef:'e',createdAt:'2026-01-01T00:00:00Z',historical:true});expect(h.status).toBe('legacy');expect(h.lastUpdate).toBe(h.createdAt);expect(h.lastBlocker).toBeUndefined()})
 it('persists release, actor, owner and reads it back idempotently',async()=>{const file=await fixture(); const input={action:'release' as const,correlationId:'corr-fixed',cause:'causa',solution:'solução',nextAction:'próximo',owner:'Gabe'}; const first=await resumeHandoff('local-handoff',input,{actor:'Íris',scope:'local'},file); expect(first.handoff?.status).toBe('awaiting_owner'); expect(first.handoff?.lastRelease).toBeTruthy(); expect(first.handoff?.lastUpdate).toBeTruthy(); expect(first.event).toMatchObject({actor:'Íris',owner:'Gabe',nextAction:'próximo',correlationId:'corr-fixed',solution:{resolutionPlan:'solução'}}); const second=await resumeHandoff('local-handoff',input,{actor:'Íris',scope:'local'},file); expect(second.idempotent).toBe(true); expect((await getSnapshot(file)).handoffs.find(h=>h.id==='local-handoff')?.status).toBe('awaiting_owner')})
 it('resumes legacy by creating an operational handoff without mutating the legacy record',async()=>{const file=await fixture(); const state=JSON.parse(await readFile(file,'utf8')); state.handoffs[0].status='legacy'; state.handoffs[0].historical=true; await writeFile(file,JSON.stringify(state)); const first=await resumeLegacyHandoff('local-handoff',{correlationId:'legacy-corr'},{actor:'Íris',scope:'local'},file); expect(first.handoff).toMatchObject({status:'in_progress',correlationId:'legacy-corr',to:'Gabe',nextStep:'revisar'}); const persisted=await getSnapshot(file); const preserved=persisted.handoffs.find(h=>h.id==='local-handoff'); expect(preserved).toMatchObject({status:'legacy',historical:true,solution:state.handoffs[0].solution,nextStep:'revisar'}); expect(preserved?.id).toBe('local-handoff'); const second=await resumeLegacyHandoff('local-handoff',{correlationId:'legacy-corr'},{actor:'Íris',scope:'local'},file); expect(second.idempotent).toBe(true); expect(second.handoff?.id).toBe(first.handoff?.id); const saved=JSON.parse(await readFile(file,'utf8')) as FluxState; expect(saved.events.filter(e=>e.correlationId==='legacy-corr')).toHaveLength(1)})
 it('imports mirrored roots without duplicate IDs and does not alter the clean fixture',async()=>{const dir=await mkdtemp(join(tmpdir(),'handoff-roots-')); dirs.push(dir); const rootA=join(dir,'a'); const rootB=join(dir,'b'); const { mkdir }=await import('node:fs/promises'); await mkdir(rootA); await mkdir(rootB); const block='de: Íris\npara: Gabe\ncard: AF-001\nresumo: Espelho\npróximo passo: revisar\n'; await writeFile(join(rootA,'one.md'),block); await writeFile(join(rootB,'mirror.md'),block); const state={version:1,projects:[],cards:[],approvals:[],gates:[],events:[],handoffs:[],artifacts:[]}; const result=await syncHandoffs(state,[rootA,rootB]); expect(result).toHaveLength(1); expect(state.handoffs).toHaveLength(1); const fixtureState=JSON.parse(await readFile(join(process.cwd(),'data/after-forty-intake.fixture.json'),'utf8')) as FluxState; expect(fixtureState.handoffs.filter(h=>h.historical)).toHaveLength(0); const synced=await syncHandoffs(fixtureState,[rootA,rootB]); expect(synced).toHaveLength(3); expect(new Set(synced.map(h=>h.id)).size).toBe(3)})
 it('keeps legacy handoffs read-only',async()=>{const file=await fixture(); const state=JSON.parse(await readFile(file,'utf8')); state.handoffs[0].status='legacy'; state.handoffs[0].historical=true; await writeFile(file,JSON.stringify(state)); await expect(resumeHandoff('local-handoff',{action:'resume',correlationId:'c',cause:'x',solution:'y',nextAction:'z',owner:'Gabe'},{actor:'Íris',scope:'local'},file)).rejects.toMatchObject({code:'LEGACY_HANDOFF'})})
})
