import type { FluxState, ResolutionAction } from '../src/lib/flux-repository'
export const stamp='2026-09-17T00:00:00.000Z'
export const action: ResolutionAction={from:'Íris',to:'Théo',objective:'Implement',deliverable:'SQL',acceptanceCriteria:'Tests pass',evidenceRequired:'test output',nextStep:'Execute tests',fallback:'Ask Sergio'}
export const solution={cause:'schema gap',owner:'Théo',nextAction:'implement',resolutionPlan:'Add columns',resolutionEvidence:'tests'}
export function fullState(): FluxState {
  return {
    version:0,
    projects:[{id:'project-BUSINESS',name:'Project title',tenantId:'tenant-business',status:'active',owner:'Kora',description:'Briefing'}],
    cards:[{id:'CARD-1',project:'Project title',tenantId:'tenant-business',title:'Implement',status:'awaiting_owner',assignee:'Théo',priority:'high',detail:'Detailed objective',acceptanceCriteria:['first','second'],updatedAt:stamp}],
    approvals:[{id:'approval-1',cardId:'CARD-1',tenantId:'tenant-business',title:'Permission',requestedBy:'Kora',impact:'No external effect',scope:'concept',rollback:'revert',status:'approved',decidedAt:stamp,decidedBy:'Sergio'}],
    gates:[{id:'gate-1',cardId:'CARD-1',project:'Project title',title:'Gate',requiredDecision:'Scope',status:'pending',impact:'local',cost:'none',scope:'concept',reversibility:'yes',rollback:'reopen',evidence:['ref'],owner:'Sergio',requestedAt:stamp,externalActionAuthorized:false,blockers:['approval needed']}],
    jobs:[{jobId:'JOB-1',cardId:'CARD-1',project:'Project title',tenantId:'tenant-business',agent:'Théo',role:'Engineer',objective:'SQL',status:'in_progress',startedAt:stamp,updatedAt:stamp,completedAt:stamp,artifactRefs:['artifact-1'],handoffRefs:['handoff-1'],evidenceRefs:['evidence'],blockers:['schema gap'],nextStep:'Test',correlationId:'NOT-A-UUID',source:'webhook',sourceType:'live',historical:false,activeBlocker:true,lastSeen:stamp,lastActivity:'Implementing',nextCheck:'after readback',progress:20,currentStep:'Add migration',owner:'Théo',lastEvent:'progress',verification:'not_verified',dependsOn:[],blocks:[],canStart:true,parallelGroup:'group',track:'backend',dependencyReason:'none'}],
    handoffs:[{id:'handoff-1',cardId:'CARD-1',project:'Project title',from:'Íris',to:'Théo',summary:'Implement SQL',done:'Schema reviewed',decisions:['use PostgreSQL'],risks:'No remote permission',nextStep:'Test',nextCheck:'after test',lastActivity:'review',acceptanceCriteria:'readback matches',evidenceRef:'evidence',createdAt:stamp,status:'received',lastUpdate:stamp,lastBlocker:'schema gap',lastRelease:stamp,blockerId:'blocker-1',jobId:'JOB-1',correlationId:'NOT-A-UUID',forwardingKey:'business-key',resolutionAction:action,interaction:{...action,actor:'Íris',type:'instruction',status:'ready',decision:'ready',message:'Implement SQL now'},solution,sourceType:'local',historical:false,legacy:false,source:'api',activeBlocker:true,blockers:[{id:'blocker-nested',cause:'nested cause',status:'legacy'}]}],
    artifacts:[{id:'artifact-1',cardId:'CARD-1',name:'evidence.txt',kind:'text',status:'available',path:'db:artifact-1',sourcePath:'uploaded',size:8}],
    blockers:[{id:'blocker-1',sourceId:'handoff-1',cardId:'CARD-1',cause:'schema gap',status:'open',owner:'Théo',author:'Íris',nextAction:'Implement',resolutionPlan:'Add columns',resolutionEvidence:'tests',resolution:'forwarded',verification:'verified',resolutionAction:action}],
    sprints:[{id:'sprint-1',projectId:'project-BUSINESS',tenantId:'tenant-business',name:'Sprint',objective:'Ship schema',status:'active',owner:'Kora',startsAt:stamp,endsAt:stamp,dependencies:[],nextCheck:'after QA',createdAt:stamp,updatedAt:stamp}],
    stories:[{id:'story-1',sprintId:'sprint-1',projectId:'project-BUSINESS',tenantId:'tenant-business',title:'Schema',objective:'Persist relational',owner:'Théo',acceptanceCriteria:['test'],status:'in_progress',cardIds:['CARD-1'],jobIds:['JOB-1'],evidenceRefs:['evidence'],blockerIds:['blocker-1'],nextCheck:'after QA',createdAt:stamp,updatedAt:stamp}],
    requiredActions:[{id:'required-1',dedupeKey:'dedupe',what:'Test',why:'Verify',who:'Théo',from:'Íris',to:'Théo',objective:'Readback',deliverable:'Evidence',acceptanceCriteria:'pass',dueCheck:'after write',fallback:'Sergio',status:'hold',reasonCode:'BLOCKER_OPEN',correlationId:'business-correlation',createdAt:stamp,updatedAt:stamp}],
    coordinator:{waitingReasons:['awaiting QA'],lastCoordinatorRun:{correlationId:'coordinator-correlation',startedAt:stamp,completedAt:stamp,heartbeat:stamp,lastActivity:stamp,idleDetected:0,dispatched:1,holds:2,requiredActions:1,waitingReasons:['gate'],result:'completed',lastCheck:'last check',nextFollowUp:'next followup',unanswered:2,backlogActionable:3}},
    events:[{id:'event-1',time:stamp,actor:'Íris',action:'forwarded blocker',cardId:'CARD-1',correlationId:'event-correlation',fromStatus:'blocked',toStatus:'awaiting_owner',reason:'Implement',blockerId:'blocker-1',jobId:'JOB-1',handoffId:'handoff-1',from:'Íris',to:'Théo',owner:'Théo',nextAction:'Test',solution,resolutionAction:action,receipt:{correlationId:'receipt-correlation',operation:'blocker.forward',status:'completed',actor:'Íris',jobId:'JOB-1',startedAt:stamp,completedAt:stamp,durationMs:0,metadata:{blockerId:'blocker-1',handoffId:'handoff-1'}}}],
  }
}
